[package]
name = "smoothsend"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
smoothsend = "0x82547f5454cbd6f92ee8715c229deea4dafca67fbf31ce817cf91c90f9c4fd82"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"